services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOSTNAME=0.0.0.0
    volumes:
      # Mount source code for hot reload
      - .:/app
      # Prevent node_modules from being overwritten
      - /app/node_modules
    restart: unless-stopped
    # Optional: for better development experience
    stdin_open: true
    tty: true
