services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOSTNAME=0.0.0.0
    volumes:
      # Mount only source code and public assets for hot reload
      - ./src:/app/src
      - ./public:/app/public
      - ./components:/app/components
      # Keep node_modules in a Docker-managed volume
      - /app/node_modules
    restart: unless-stopped
    # Optional: for better development experience
    stdin_open: true
    tty: true
