onlyBuiltDependencies:
  - '@vercel/speed-insights'
  - esbuild
  - sharp
overrides:
  esbuild@<=0.24.2: '>=0.25.0'
  vite@>=6.1.0 <6.1.2: '>=6.1.2'
  vite@>=6.1.0 <6.1.3: '>=6.1.3'
  vite@>=6.1.0 <6.1.4: '>=6.1.4'
  vite@>=6.1.0 <6.1.5: '>=6.1.5'
  '@babel/runtime@<7.26.10': '>=7.26.10'
  '@babel/helpers@<7.26.10': '>=7.26.10'
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
